# Generated by Django 4.2.6 on 2023-10-25 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                (
                    "pseudo",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("mdp", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("adresse", models.CharField(max_length=255)),
                ("last_login", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UtilisateurSession",
            fields=[
                ("id_session", models.IntegerField(primary_key=True, serialize=False)),
                ("last_login", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utilisateur.utilisateur",
                    ),
                ),
            ],
        ),
    ]
