# Generated by Django 4.2.6 on 2023-12-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_utilisateur_cycle_utilisateur_programme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateursession',
            name='id_session',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
