# Generated by Django 4.2.6 on 2023-12-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateurs',
            new_name='Admin_Admission',
        ),
    ]
