# Generated by Django 4.2.6 on 2023-10-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateur", "0002_utilisateur_groups_utilisateur_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilisateur",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="utilisateur",
            name="user_permissions",
        ),
    ]
