# Generated by Django 4.2.6 on 2023-11-01 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programme", "0001_initial"),
        ("cycle", "0001_initial"),
        ("session", "0001_initial"),
        ("utilisateur", "0003_remove_utilisateur_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="cycle",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cycle.cycle",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="programme",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="programme.programme",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="session.session",
            ),
            preserve_default=False,
        ),
    ]
