# Generated by Django 4.2.6 on 2023-11-01 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateur", "0003_remove_utilisateur_groups_and_more"),
        ("session", "0001_initial"),
        ("cours", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="credit",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cours",
            name="nom_prof",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Cours_Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_ase", models.DateField()),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="cours.cours"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="session.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cours_Etudiants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit", models.IntegerField(default=-1)),
                ("date_inscription", models.DateTimeField()),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="cours.cours"
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="utilisateur.utilisateur",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="session.session",
                    ),
                ),
            ],
        ),
    ]
