# Generated by Django 4.2.6 on 2023-11-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0002_cours_credit_cours_nom_prof_cours_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="dispenseEn",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
