# Generated by Django 4.2.6 on 2023-11-07 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(choices=[('Génie logiciel', 'Génie logiciel'), ('Développement web', 'Développement web'), ('Analyse de données en biologie', 'Analyse de données en biologie'), ("Systèmes d'informatique en réseaux", "Systèmes d'informatique en réseaux"), ('Méthodes statistiques', 'Méthodes statistiques'), ('Mathématiques appliquées', 'Mathématiques appliquées'), ('Génie électrique', 'Génie électrique'), ('Design industriel', 'Design industriel'), ('Sciences politiques', 'Sciences politiques'), ('Études en intelligence artificielle', 'Études en intelligence artificielle')], max_length=100)),
                ('type_admission', models.CharField(choices=[('Baccalauréat', 'Baccalauréat'), ('Master', 'Master'), ('Doctorat', 'Doctorat'), ('Maîtrise', 'Maîtrise')], max_length=50)),
                ('cycle', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50)),
                ('description', models.TextField()),
                ('credits_programme', models.IntegerField()),
                ('objectifs', models.TextField()),
                ('duree_programme', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Hiver', 'Hiver'), ('Été', 'Été'), ('Automne', 'Automne')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeTrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demande_admission.programme')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demande_admission.trimestre')),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='trimestres',
            field=models.ManyToManyField(related_name='programmes', through='demande_admission.ProgrammeTrimestre', to='demande_admission.trimestre'),
        ),
    ]
