# Generated by Django 4.2.6 on 2023-11-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande_admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimestre',
            name='annee',
            field=models.IntegerField(default=2023),
        ),
    ]
