# Generated by Django 4.2.6 on 2023-11-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande_admission', '0002_trimestre_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='prix_Programme',
            field=models.FloatField(default=36000.0, max_length=8),
        ),
    ]
