# Generated by Django 4.2.6 on 2023-11-10 17:16

import demande_admission.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demande_admission', '0003_programme_prix_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordonne_Bancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifiant', models.CharField(max_length=100, verbose_name='Nom sur la Carte ')),
                ('num_Bancaire', models.CharField(max_length=250, verbose_name='Numéro de banque')),
                ('code_banque', models.CharField(max_length=10, verbose_name='Code Banque')),
                ('date_expiration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Document_Fournir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releve_note', models.FileField(upload_to=demande_admission.models.chemin_telechargement)),
                ('attestation', models.FileField(upload_to=demande_admission.models.chemin_telechargement)),
                ('lettre_motivation', models.FileField(upload_to=demande_admission.models.chemin_telechargement)),
                ('piece_identite', models.FileField(upload_to=demande_admission.models.chemin_telechargement)),
                ('acte_Naissance', models.FileField(upload_to=demande_admission.models.chemin_telechargement)),
            ],
        ),
        migrations.CreateModel(
            name='Information_Personnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=256)),
                ('nationalite', models.CharField(max_length=30)),
                ('adresse', models.TextField()),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sexe', models.CharField(max_length=1)),
                ('status_Matrimoniale', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode_paiement', models.CharField(max_length=100)),
                ('frais_admission', models.FloatField(max_length=6)),
                ('datelimite', models.DateField()),
                ('numero_paiement', models.CharField(max_length=25)),
                ('Coordonne_Bancaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demande_admission.coordonne_bancaire')),
            ],
        ),
    ]
