# Generated by Django 4.2.6 on 2023-11-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0001_initial'),
        ('demande_admission', '0004_coordonne_bancaire_document_fournir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demander_Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Soumision', models.DateField()),
                ('statut_demande', models.CharField(choices=[('accepte', 'Accepté'), ('refus', 'Refusé'), ('attente', 'En Attente')], default='attente', max_length=10)),
                ('Document_Fournir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demande_admission.document_fournir')),
                ('Information_Personnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demande_admission.information_personnelle')),
                ('Paiement_Admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demande_admission.paiement')),
                ('ProgrammeTrimestre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demande_admission.programmetrimestre')),
                ('demandeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Utilisateurs.utilisateurs')),
            ],
        ),
    ]
