# Generated by Django 4.2.6 on 2023-11-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande_admission', '0008_alter_demander_admission_document_fournir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_personnelle',
            name='sexe',
            field=models.CharField(max_length=8),
        ),
    ]
